// Pure logic for the curated-media snapshot pipeline. No IO here — the CLI
// (scripts/snapshot-media.mjs) handles the filesystem/git/network so this
// module stays unit-testable with `node --test`.

const IMAGE_EXTS = new Set(['jpg', 'jpeg', 'png', 'webp', 'heic']);
const VIDEO_EXTS = new Set(['mp4', 'mov']);

/**
 * storage: plain object of AsyncStorage key → string value (the CLI reads
 * this out of the simulator's RCTAsyncLocalStorage manifest + spill files).
 * Returns [{ slot, uri, type }] for every curated-able media value found.
 */
export function collectSlots(storage) {
  const slots = [];
  const json = (key) => {
    try {
      const raw = storage[key];
      return raw ? JSON.parse(raw) : null;
    } catch {
      return null;
    }
  };

  // Banners: v2 { uri, type } preferred, legacy v1 bare video URI fallback.
  for (const [slot, v2Key, v1Key] of [
    ['profile-banner', 'proslync:profile:banner:v2', 'proslync:profile:bannerVideo:v1'],
    ['coach-banner', 'proslync:coachprofile:banner:v2', 'proslync:coachprofile:bannerVideo:v1'],
  ]) {
    const v2 = json(v2Key);
    if (v2 && v2.uri) {
      slots.push({ slot, uri: v2.uri, type: v2.type === 'video' ? 'video' : 'image' });
    } else if (storage[v1Key]) {
      slots.push({ slot, uri: storage[v1Key], type: 'video' });
    }
  }

  const covers = json('proslync:home:coverMedia:v2') || {};
  for (const [id, m] of Object.entries(covers)) {
    if (m && m.uri) {
      slots.push({ slot: `cover-${id}`, uri: m.uri, type: m.type === 'video' ? 'video' : 'image' });
    }
  }

  const logos = json('proslync:home:customLogos:v1') || {};
  for (const [id, uri] of Object.entries(logos)) {
    if (uri) slots.push({ slot: `logo-${id}`, uri, type: 'image' });
  }

  const avatar = storage['proslync:profile:avatar:v1'];
  if (avatar) slots.push({ slot: 'profile-avatar', uri: avatar, type: 'image' });

  return slots;
}

/** Lower-cased extension if whitelisted for the media type, else null. */
export function classifyExt(uri, type) {
  const base = uri.split('?')[0].split('/').pop() || '';
  if (!base.includes('.')) return null;
  const ext = base.split('.').pop().toLowerCase();
  const ok = type === 'video' ? VIDEO_EXTS : IMAGE_EXTS;
  return ok.has(ext) ? ext : null;
}

const ENTRY_RE = /^\s*'([^']+)': \{ type: '(image|video)', (?:uri: '([^']+)'|source: require\('([^']+)'\)) \},$/;

/**
 * Parses entries back out of a generated curated-manifest.ts. Only matches
 * the exact line format renderManifest emits — hand-edits are not supported
 * (the file header says "do not edit by hand").
 */
export function parseManifestEntries(src) {
  const entries = {};
  for (const line of src.split('\n')) {
    const m = ENTRY_RE.exec(line);
    if (!m) continue;
    const [, slot, type, url, requirePath] = m;
    entries[slot] = type === 'video' ? { type, url } : { type, requirePath };
  }
  return entries;
}

/** Renders the full curated-manifest.ts source from an entries map. */
export function renderManifest(entries) {
  const lines = Object.keys(entries)
    .sort()
    .map((slot) => {
      const e = entries[slot];
      return e.type === 'video'
        ? `  '${slot}': { type: 'video', uri: '${e.url}' },`
        : `  '${slot}': { type: 'image', source: require('${e.requirePath}') },`;
    });
  const body = lines.length ? `{\n${lines.join('\n')}\n}` : '{}';
  return `// AUTO-GENERATED by scripts/snapshot-media.mjs — do not edit by hand.
// Run \`npm run snapshot-media\` after curating media in the simulator.
import type { ImageSourcePropType } from 'react-native';

export type CuratedMediaEntry =
  | { type: 'image'; source: ImageSourcePropType } // bundled in the app binary
  | { type: 'video'; uri: string }; // hosted, SHA-pinned CDN URL

export const CURATED_MEDIA: Record<string, CuratedMediaEntry> = ${body};
`;
}
