import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  collectSlots,
  classifyExt,
  parseManifestEntries,
  renderManifest,
} from './snapshot-core.mjs';

test('collectSlots reads v2 banner keys, covers, logos, avatar', () => {
  const storage = {
    'proslync:profile:banner:v2': JSON.stringify({ uri: 'file:///a/Documents/proslync-media/profile-banner/1.mp4', type: 'video' }),
    'proslync:coachprofile:bannerVideo:v1': 'file:///a/Documents/proslync-media/coach-banner/2.mov',
    'proslync:home:coverMedia:v2': JSON.stringify({ ncaab: { uri: 'file:///a/Documents/proslync-media/cover-ncaab/3.jpg', type: 'image' } }),
    'proslync:home:customLogos:v1': JSON.stringify({ ncaab: 'file:///a/Documents/proslync-media/logo-ncaab/4.png' }),
    'proslync:profile:avatar:v1': 'file:///a/Documents/proslync-media/profile-avatar/5.jpg',
  };
  const slots = collectSlots(storage);
  assert.deepEqual(
    slots.sort((x, y) => x.slot.localeCompare(y.slot)),
    [
      { slot: 'coach-banner', uri: 'file:///a/Documents/proslync-media/coach-banner/2.mov', type: 'video' },
      { slot: 'cover-ncaab', uri: 'file:///a/Documents/proslync-media/cover-ncaab/3.jpg', type: 'image' },
      { slot: 'logo-ncaab', uri: 'file:///a/Documents/proslync-media/logo-ncaab/4.png', type: 'image' },
      { slot: 'profile-avatar', uri: 'file:///a/Documents/proslync-media/profile-avatar/5.jpg', type: 'image' },
      { slot: 'profile-banner', uri: 'file:///a/Documents/proslync-media/profile-banner/1.mp4', type: 'video' },
    ],
  );
});

test('collectSlots prefers v2 over legacy v1 and skips empty maps', () => {
  const storage = {
    'proslync:profile:banner:v2': JSON.stringify({ uri: 'file:///x/v2.mp4', type: 'video' }),
    'proslync:profile:bannerVideo:v1': 'file:///x/v1.mp4',
    'proslync:home:coverMedia:v2': '{}',
  };
  const slots = collectSlots(storage);
  assert.equal(slots.length, 1);
  assert.equal(slots[0].uri, 'file:///x/v2.mp4');
});

test('collectSlots tolerates corrupt JSON and missing keys', () => {
  assert.deepEqual(collectSlots({}), []);
  assert.deepEqual(collectSlots({ 'proslync:home:coverMedia:v2': 'not-json{{{' }), []);
});

test('classifyExt whitelists and falls back', () => {
  assert.equal(classifyExt('file:///a/b/x.MP4', 'video'), 'mp4');
  assert.equal(classifyExt('file:///a/b/x.mov', 'video'), 'mov');
  assert.equal(classifyExt('file:///a/b/x.avi', 'video'), null);
  assert.equal(classifyExt('file:///a/b/x.jpeg', 'image'), 'jpeg');
  assert.equal(classifyExt('file:///a/b/x.heic', 'image'), 'heic');
  assert.equal(classifyExt('file:///a/b/x.bmp', 'image'), null);
  assert.equal(classifyExt('file:///a/b/noext', 'image'), null);
  assert.equal(classifyExt('file:///a/b/x.jpg?size=2', 'image'), 'jpg');
});

test('renderManifest → parseManifestEntries round-trips', () => {
  const entries = {
    'profile-banner': { type: 'video', url: 'https://cdn.jsdelivr.net/gh/o/r@abc123/public/videos/curated/profile-banner.mp4' },
    'cover-ncaab': { type: 'image', requirePath: '../../assets/media/curated/cover-ncaab.jpg' },
  };
  const src = renderManifest(entries);
  assert.ok(src.includes('export const CURATED_MEDIA'));
  assert.ok(src.includes("'profile-banner': { type: 'video', uri: 'https://cdn.jsdelivr.net/gh/o/r@abc123/public/videos/curated/profile-banner.mp4' },"));
  assert.ok(src.includes("'cover-ncaab': { type: 'image', source: require('../../assets/media/curated/cover-ncaab.jpg') },"));
  assert.deepEqual(parseManifestEntries(src), entries);
});

test('renderManifest sorts slots and matches the committed empty-manifest shape', () => {
  const empty = renderManifest({});
  assert.ok(empty.includes('// AUTO-GENERATED by scripts/snapshot-media.mjs — do not edit by hand.'));
  assert.ok(empty.includes("import type { ImageSourcePropType } from 'react-native';"));
  assert.deepEqual(parseManifestEntries(empty), {});
  const src = renderManifest({ b: { type: 'video', url: 'https://x/b.mp4' }, a: { type: 'video', url: 'https://x/a.mp4' } });
  assert.ok(src.indexOf("'a':") < src.indexOf("'b':"));
});

test('merge semantics: spread keeps untouched entries', () => {
  const existing = { a: { type: 'video', url: 'https://old' }, b: { type: 'image', requirePath: '../../assets/media/curated/b.jpg' } };
  const fresh = { a: { type: 'video', url: 'https://new' } };
  const merged = { ...existing, ...fresh };
  assert.equal(merged.a.url, 'https://new');
  assert.equal(merged.b.requirePath, '../../assets/media/curated/b.jpg');
});
