// AUTO-GENERATED by scripts/snapshot-media.mjs — do not edit by hand.
// Run `npm run snapshot-media` after curating media in the simulator.
import type { ImageSourcePropType } from 'react-native';

export type CuratedMediaEntry =
  | { type: 'image'; source: ImageSourcePropType } // bundled in the app binary
  | { type: 'video'; uri: string }; // hosted, SHA-pinned CDN URL

export const CURATED_MEDIA: Record<string, CuratedMediaEntry> = {};
