// AUTO-GENERATED by scripts/snapshot-media.mjs — do not edit by hand.
// Run `npm run snapshot-media` after curating media in the simulator.
import type { ImageSourcePropType } from 'react-native';

export type CuratedMediaEntry =
  | { type: 'image'; source: ImageSourcePropType } // bundled in the app binary
  | { type: 'video'; uri: string }; // hosted, SHA-pinned CDN URL

export const CURATED_MEDIA: Record<string, CuratedMediaEntry> = {
  'coach-banner': { type: 'video', uri: 'https://arshiarahnavard7-sys.github.io/proslync-web-v1.1/public/videos/curated/coach-banner.mov' },
  'cover-awards': { type: 'image', source: require('../../assets/media/curated/cover-awards.png') },
  'cover-nba': { type: 'video', uri: 'https://arshiarahnavard7-sys.github.io/proslync-web-v1.1/public/videos/curated/cover-nba.mov' },
  'cover-ncaab': { type: 'video', uri: 'https://arshiarahnavard7-sys.github.io/proslync-web-v1.1/public/videos/curated/cover-ncaab.mov' },
  'logo-awards': { type: 'image', source: require('../../assets/media/curated/logo-awards.jpg') },
  'logo-ncaab': { type: 'image', source: require('../../assets/media/curated/logo-ncaab.jpg') },
  'profile-banner': { type: 'video', uri: 'https://arshiarahnavard7-sys.github.io/proslync-web-v1.1/public/videos/curated/profile-banner.mov' },
};
